### ISSUE TITLE
Matterport Evaluation Error

### ISSUE THREAD

**Issue by HustQBW** [pengsongyou/openscene#11]
Hello, when I evaluate on the Matterport Dataset, there is an error raised like:
`Traceback (most recent call last):
  File "run/evaluate_modify.py", line 409, in <module>
    main()
  File "run/evaluate_modify.py", line 138, in main
    main_worker(args.test_gpu, args.ngpus_per_node, args)
  File "run/evaluate_modify.py", line 234, in main_worker
    evaluate(model, val_loader, dataset_name)
  File "run/evaluate_modify.py", line 403, in evaluate
    accumu_iou = metric.evaluate(store_logit.numpy(),
  File "/home/qbw/research/multi-modal/openscene/util/metric.py", line 64, in evaluate
    confusion = confusion_matrix(pred_ids, gt_ids, N_CLASSES)
  File "/home/qbw/research/multi-modal/openscene/util/metric.py", line 23, in confusion_matrix
    return np.bincount(
ValueError: cannot reshape array of size 442 into shape (21,21)`

I run np.unique(gt_ids) and find that 21 in gt_ids. 
np.unique(gt_ids)
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21])

This way, when computing confusion_matrix,`pred_ids[idxs] * num_classes + gt_ids[idxs]` will be in range [0,441]. So the shape is 442, can't reshape.

Do you know the inner reason? Thanks for reply!

**Comment by HustQBW** [comment]
I also find that, in scannet, the gt_ids:
'(Pdb) np.unique(gt_ids)
array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 255])'

The additonal 'unlabelled' class is set to 255. But in matterport, not set to 255.

Probably, this lead to the above question?

**Comment by HustQBW** [comment]
Oh, I think I've found the reason. When vis_gt, the label==255 will be set to len(labelset)-1. I think this will destroy the confusion_matrix computation. It's really embarrasing. Sorry for the interrupt!
