### ISSUE TITLE
Issue running evaluation on AWS: version `GLIBC_2.33' not found

### ISSUE THREAD

**Issue by dokooh** [pengsongyou/openscene#71]
Hi, 

I have managed to follow the installation completely without any issue on AWS SageMaker and when I run eval code on matter port config, I get this output: 

```
!sh run/eval.sh /out config/matterport/test_160classes.yaml ensemble
+ exp_dir=/out
+ config=config/matterport/test_160classes.yaml
+ feature_type=ensemble
+ mkdir -p /out
+ result_dir=/out/result_eval
+ export PYTHONPATH=.
+ python -u run/evaluate.py --config=config/matterport/test_160classes.yaml feature_type ensemble save_folder /out/result_eval
+ date +%Y%m%d_%H%M
+ tee -a /out/eval-20240108_1435.log
Traceback (most recent call last):
  File "run/evaluate.py", line 23, in <module>
    from run.distill import get_model
  File "/root/LIDAR/openscene/openscene/run/distill.py", line 24, in <module>
    from dataset.feature_loader import FusedFeatureLoader, collation_fn
  File "/root/LIDAR/openscene/openscene/dataset/feature_loader.py", line 8, in <module>
    import SharedArray as SA
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/conda/lib/python3.8/site-packages/SharedArray.cpython-38-x86_64-linux-gnu.so)
```
Did some googling but none of the approaches helped. 
Thanks for your help and attention. 

**Environment:**
_AWS sagemaker studio
Env: Pytorch 1.12/Python 3.8  
Kernel: Python 3
VM: ML.g4dn.xlarge 4vCPU 1GPU 16GiB RAM_

**Comment by pengsongyou** [comment]
Can you simply comment out `import SharedArray as SA`, it is by default not used actually.

**Comment by dokooh** [comment]
Thanks that did the job. 

Do I need to download the checkpoint myself? I tested ensemble first and gave the same error. Kindly let me know where to grab the PTH file. Thanks a lot.

```
+ exp_dir=/out
+ config=config/matterport/test_160classes.yaml
+ feature_type=distill
+ mkdir -p /out
+ result_dir=/out/result_eval
+ export PYTHONPATH=.
+ python -u run/evaluate.py --config=config/matterport/test_160classes.yaml feature_type distill save_folder /out/result_eval
+ date +%Y%m%d_%H%M
+ tee -a /out/eval-20240111_1156.log
torch.__version__:1.7.1+cu110
torch.version.cuda:11.0
torch.backends.cudnn.version:8005
torch.backends.cudnn.enabled:True
[2024-01-11 11:56:13,260 evaluate.py line 154] arch_3d: MinkUNet18A
classes: 160
data_root: data/matterport_3d_160
data_root_2d_fused_feature: data/matterport_multiview_openseg_test
dist_backend: nccl
dist_url: tcp://127.0.0.1:6787
distributed: False
feature_2d_extractor: openseg
feature_type: distill
input_color: False
manual_seed: 3407
mark_no_feature_to_unknown: True
model_path: None
multiprocessing_distributed: False
ngpus_per_node: 1
prompt_eng: True
rank: 0
save_feature_as_numpy: False
save_folder: /out/result_eval
split: test
sync_bn: False
test_batch_size: 1
test_gpu: [0]
test_repeats: 1
test_workers: 8
use_apex: False
use_shm: False
vis_gt: True
vis_input: True
vis_pred: True
voxel_size: 0.02
world_size: 1
Traceback (most recent call last):
  File "run/evaluate.py", line 428, in <module>
    main()
  File "run/evaluate.py", line 138, in main
    main_worker(args.test_gpu, args.ngpus_per_node, args)
  File "run/evaluate.py", line 196, in main_worker
    raise RuntimeError("=> no checkpoint found at '{}'".format(args.model_path))
RuntimeError: => no checkpoint found at 'None'
```

**Comment by pengsongyou** [comment]
I never ran into such an error, it might be related to no internet within AWS? Not sure. You probably want to download it first. Check [here](https://github.com/pengsongyou/openscene/blob/main/config/matterport/ours_openseg_pretrained.yaml#L46)

**Comment by dokooh** [comment]
Thanks a lot, 
I think it's because you haven't added any pretrained value to the model_path in the matterport class configs.

I tested your openseg yaml file, and it finds the PTH files but stops execution when it runs into empty scenes (0 featured ones), anyway to bypass the empty ones? 

```
+ exp_dir=/out
+ config=config/matterport/ours_openseg_pretrained.yaml
+ feature_type=ensemble
+ mkdir -p /out
+ result_dir=/out/result_eval
+ export PYTHONPATH=.
+ python -u run/evaluate.py --config=config/matterport/ours_openseg_pretrained.yaml feature_type ensemble save_folder /out/result_eval
+ date +%Y%m%d_%H%M
+ tee -a /out/eval-20240116_1022.log
torch.__version__:1.7.1+cu110
torch.version.cuda:11.0
torch.backends.cudnn.version:8005
torch.backends.cudnn.enabled:True
[2024-01-16 10:23:03,250 evaluate.py line 154] arch_3d: MinkUNet18A
aug: True
base_lr: 0.0001
batch_size: 8
batch_size_val: 1
classes: 21
data_root: data/matterport_3d
data_root_2d_fused_feature: data/matterport_multiview_openseg_test
dist_backend: nccl
dist_url: tcp://127.0.0.1:6787
distributed: False
epochs: 100
eval_freq: 1
evaluate: True
feature_2d_extractor: openseg
feature_type: ensemble
ignore_label: 255
input_color: False
loop: 5
loss_type: cosine
manual_seed: 3407
mark_no_feature_to_unknown: True
model_path: https://cvg-data.inf.ethz.ch/openscene/models/matterport_openseg.pth.tar
momentum: 0.9
multiprocessing_distributed: False
ngpus_per_node: 1
power: 0.9
print_freq: 10
prompt_eng: True
rank: 0
resume: None
save_feature_as_numpy: False
save_folder: /out/result_eval
save_freq: 1
save_path: None
split: test
start_epoch: 0
sync_bn: False
test_batch_size: 1
test_gpu: [0]
test_repeats: 5
test_workers: 8
train_gpu: [0]
use_apex: False
use_shm: False
vis_gt: True
vis_input: True
vis_pred: True
voxel_size: 0.02
workers: 8
world_size: 1
.. 
Traceback (most recent call last):
  File "run/evaluate.py", line 428, in <module>
    main()
  File "run/evaluate.py", line 138, in main
    main_worker(args.test_gpu, args.ngpus_per_node, args)
  File "run/evaluate.py", line 204, in main_worker
    val_data = FusedFeatureLoader(datapath_prefix=args.data_root,
  File "/root/LIDAR/openscene/openscene/dataset/feature_loader.py", line 62, in __init__
    raise Exception('0 file is loaded in the feature loader.')
Exception: 0 file is loaded in the feature loader.
```
